---
title: "Course support"
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures

If you have a question during lecture, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

The teaching team is here to help you be successful in the course. You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so office hours are a valuable resource. I encourage each and every one of you to take advantage of this resource! Make a pledge to stop by office hours at least once during the first three weeks of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself. You can find a list of everyone's office hours [here](/course-team.html).

## Discussion forum

Have a question that can't wait for office hours? Prefer to write out your question in detail rather than asking in person? The online discussion forum is the best venue for these! We will use [Ed discussion](https://edstem.org/us/courses/27622/discussion/) as the online discussion forum. There is a chance another student has already asked a similar question, so please check the other posts on Ed Discussion before adding a new question. If you know the answer to a question that is posted, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go [Ed discussion](https://edstem.org/us/courses/27622/discussion/)), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.). For such matters, you may email dr. gwynn sturdevant at [gwynnc\@wharton.upenn.edu](mailto:gwynnc@wharton.upenn.edu).

If there is a question that's not appropriate for the public forum, you are welcome to email me directly. **If you email me, please include "STAT 1010" in the subject line.** You can also contact me privately on INSERT CANVAS LINK HERE Barring extenuating circumstances, I will respond to STAT 1010 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

## Academic support

There are times you may need help with the class that is beyond what can be provided by the teaching team. In those instances, I encourage you to visit the [**Weingarten learning center**](https://wlrc.vpul.upenn.edu/). The Weingarten Center offers a variety of resources to support all Penn students in reaching their academic goals. They offer [multiple workshops](https://ulife.vpul.upenn.edu/calendar/host/weingarten-center/28) throughout the semester and students can [request workshops](https://wlrc.vpul.upenn.edu/request-a-workshop/). All services are free and confidential. To contact the Weingarten Center, call 215-573-9235. The office is located in Stouffer Commons at 3702 Spruce Street, Suite 300.

[Learning Consultations](https://wlrc.vpul.upenn.edu/lr/) offers individual consultations and group workshops that support students in developing more efficient and effective study skills and learning strategies. Learning specialists work with students to address time and project management, academic reading and writing, note-taking, problem-solving, exam preparation, test-taking, self-regulation, and flexibility.

\
[Tutoring](https://wlrc.vpul.upenn.edu/tutoring-services/) offers free access to on-campus tutors for many Penn courses in both drop-in and weekly contract format. Tutoring may be individual or in small groups. Tutors will assist with applying course information, understanding key concepts, and developing course-specific strategies. Tutoring support is available throughout the term but is best accessed early in the semester. First-time users must meet with a staff member; returning users may submit their requests online.

\
Additionally, [Marks Family Writing Center](http://writing.upenn.edu/critical/wc/) provides expert help in writing for undergraduate and graduate students. [Communication Within the Curriculum](http://www.sas.upenn.edu/cwic/) helps students express themselves orally with clarity and confidence. [Language Direct](https://plc.sas.upenn.edu/languagedirect) provides tutoring for foreign languages. [Van \
Pelt Library](http://commons.library.upenn.edu/student-support/student-assistance-services) supports students in research and instructional technologies through a range of [workshops](http://guides.library.upenn.edu/workshops) and [consultations](http://gethelp.library.upenn.edu/).

## Mental health and wellness

[Counseling and Psychological Services (CAPS)](https://www.vpul.upenn.edu/caps/) provides professional psychological and psychiatric services to students who need support in fulfilling their academic, social, and personal objectives. CAPS directly supports student mental health through counseling, crisis management, consultation, education and outreach, and training. CAPS has [a satellite office in Huntsman Hall](satellite office in  Huntsman Hall), and students with urgent concerns can talk with a CAPS clinician 24/7 at 215.898.7021 (press 1) or visit CAPS\' main office at 3624 Market Street during business hours.

\
[Student Health Service](https://www.vpul.upenn.edu/shs/) provides students with accessible, cost-effective, culturally-sensitive, and student-focused healthcare, including care for acute and chronic health problems, preventive health services, and health and wellness education.

\
[Alcohol and Other Drug Program Initiatives](https://www.vpul.upenn.edu/alcohol/) (AOD) works to reduce harm related to alcohol and other drug use at Penn.

\
[Penn Violence Prevention](https://www.vpul.upenn.edu/pvp/index.php) (PVP) engages the Penn community in the prevention of sexual violence, relationship violence, stalking, and sexual harassment on campus. PVP provides education and outreach and the staff serves as confidential resources for students.

\
[Public Safety](https://www.publicsafety.upenn.edu/safety-initiatives/): From riding your bike on campus, to preventing unattended theft, the Division of Public Safety wants to make sure you have the information you need to protect your safety and your belongings.

\
[Penn Recreation](http://www.upenn.edu/recreation/): Penn offers many opportunities for students to participate in competitive team sports and stay physically fit at state-of-the-art, world-class training centers.

\
[Wharton Wellnes](https://groups.wharton.upenn.edu/wwb/home/)s is a division-sponsored student organization that works to implement initiatives targeted at specific wellness issues in the Wharton community by creating experiences, fostering a positive culture of well-being, and connecting clubs/students to wellness resources.

\
It is important to me that you have the resources you need to be able to focus on learning in this course -- this includes both the necessary academic materials as well as taking care of your day-to-day needs. Students experiencing difficulty affording the course materials should reach out to the [Penn First Plus office](mailto:pennfirst) ([pennfirstplus\@upenn.edu](mailto:pennfirstplus@upenn.edu)). Students who are struggling to afford sufficient food to eat every day and/or lack a safe and suitable space to live should contact Student Intervention Services ([vpul-sisteam\@pobox.upenn.edu](mailto:vpul-sisteam@pobox.upenn.edu)). Students may also wish to contact their Financial Aid Counselor or Academic Advisor about these concerns. You are welcome to notify me if any of these challenges are affecting your success in this course, as long as you are comfortable doing so -- I may have resources to support you.

## **Technology accommodations** 

Students with demonstrated high financial need who have limited access to computers may request assistance in the form of loaner laptops. For technology assistance requests, please go [here](https://sis.vpul.upenn.edu/emergency-and-opportunity-funding/). Please note that supplies are limited. Additional support is also available through [Student Intervention Services](mailto:vpul-sisteam@pobox.upenn.edu).

## **Course materials costs**

There are no costs associated with this course. All readings will come from freely available, open resources (open-source textbooks, journal articles, etc.).

## **Assistance with Zoom or Canvas**

For technical help with Canvas, Gradescope, or Zoom, contact [Wharton Student Computing](https://computing.wharton.upenn.edu/). You can also access the self-service help documentation for Zoom [here](https://support.wharton.upenn.edu/help/logging-into-zoom), Canvas [here](https://support.wharton.upenn.edu/help/canvas-help-for-students), and for Gradescope [here](https://infocanvas.upenn.edu/guides/gradescope/).

Note that we will be making minimal use of Gradescope in this course (primarily for announcements and grade book). All assignment submission and discussion will take place on GitHub instead.

Zoom will be used for online office hours as well as as a backup option should we need to hold the course online instead of in person.
