---
title: "STA 1010: Introduction to Business Statistics"
---

\
This course introduces students to the discipline of statistics as a science of understanding and analyzing data. Throughout the semester, students will learn how to effectively make use\
of data in the face of uncertainty: how to collect data, how to analyze data, and how to use data to make inferences and conclusions about real world phenomena.

\
The course goals are as follows:

1.  Recognize the importance of data collection, identify limitations in data collection methods, and determine how they affect the scope of inference.

2.  Use statistical software to summarize data numerically and visually, and to perform data analysis.

3.  Have a conceptual understanding of the unified nature of statistical inference.

4.  Apply estimation and testing methods to analyze single variables or the relationship between two variables in order to understand natural phenomena and make data-based\
    decisions.

5.  Model numerical response variables using a single or multiple explanatory variables.

6.  Interpret results correctly, effectively, and in context without relying on statistical jargon.

7.  Critique data-based claims and evaluate data-based decisions.

8.  Complete a research project demonstrating mastery of statistical data analysis from exploratory analysis to inference to modeling.
