---
title: "STAT 1010: Introduction to Business Statistics"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

::: column-screen-inset-right
|           Week            | Date         | Topic                                      |                            Prepare                             |                                       Slides                                       |                                                             AE                                                              |                         HW                          | Exam | Project |                                                                                 |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| [1](/weeks/week-01.html)  | Mon, 29 Aug  | No class - opening exercises               |                                                                |                                                                                    |                                                                                                                             |                                                     |      |         |                                                                                 |
|                           | Wed, 31 Aug  | Starting with R                            |                                                                | [🖥️](/slides/01_introduction.html "Lecture slides"){aria-label="Lecture 1 slides"} |     [📋](/ae/ae-0-first_line_of_code.html "Application exercise - 1"){aria-label="Application Exercise 0 instructions"}     |                                                     |      |         |                                                                                 |
| [2](/weeks/week-02.html)  | Mon, 5 Sept  | No class - Labor Day                       |                                                                |                                                                                    |                                                                                                                             |                                                     |      |         |                                                                                 |
|                           | Wed, 7 Sept  | Continuation of Intro to R                 | [📖](/weeks/week-02.html#prepare){aria-label="Week 2 summary"} |     [🖥️](/slides/lect_02.html "Lecture slides"){aria-label="Lecture 1 slides"}     |                                                                                                                             |                                                     |      |         |                                                                                 |
| [3](/weeks/week-03.html)  | Mon, 12 Sept | Categorical variables                      | [📖](/weeks/week-03.html#prepare){aria-label="Week 2 summary"} |     [🖥️](/slides/lect_03.html "Lecture slides"){aria-label="Lecture 1 slides"}     | [📋](/ae/ae-2-exploring-categorical-vars.html "Application exercise - 2"){aria-label="Application Exercise 0 instructions"} |                                                     |      |         |                                                                                 |
|                           | Wed, 14 Sept | Numeric variables                          |                                                                |     [🖥️](/slides/lect_04.html "Lecture slides"){aria-label="Lecture 1 slides"}     |              [📋](/ae/ae-3.html "Application exercise - 3"){aria-label="Application Exercise 0 instructions"}               | [✍️](/hw/hw-6.html){aria-label="HW 5 instructions"} |      |         |                                                                                 |
| [4](/weeks/week-04.html)  | Mon, 19 Sept | Intro to probability                       | [📖](/weeks/week-04.html#prepare){aria-label="Week 2 summary"} |     [🖥️](/slides/lect_05.html "Lecture slides"){aria-label="Lecture 1 slides"}     |              [📋](/ae/ae-4.html "Application exercise - 4"){aria-label="Application Exercise 0 instructions"}               | [✍️](/hw/hw-1.html){aria-label="HW 5 instructions"} |      |         |                                                                                 |
|                           | Wed, 21 Sept | More probability rules                     |                                                                |     [🖥️](/slides/lect_06.html "Lecture slides"){aria-label="Lecture 1 slides"}     |              [📋](/ae/ae-5.html "Application exercise - 5"){aria-label="Application Exercise 0 instructions"}               |                                                     |      |         |                                                                                 |
| [5](/weeks/week-05.html)  | Mon, 26 Sept | Revision of AE 1-4                         | [📖](/weeks/week-05.html#prepare){aria-label="Week 2 summary"} |                                                                                    |              [📋](/ae/ae-6.html "Application exercise - 6"){aria-label="Application Exercise 0 instructions"}               |                                                     |      |         |                                                                                 |
|                           | Wed, 28 Sept | Revision of HW-1                           | [📖](/weeks/week-05.html#prepare){aria-label="Week 2 summary"} |                                                                                    |              [📋](/ae/ae-7.html "Application exercise - 7"){aria-label="Application Exercise 0 instructions"}               |                                                     |      |         |                                                                                 |
| [6](/weeks/week-06.html)  | Mon, 3 Oct   | Exam 1                                     |                                                                |                                                                                    |                                                                                                                             |                                                     |  ✅  |         |                                                                                 |
|                           | Wed, 5 Oct   | Random variables                           | [📖](/weeks/week-06.html#prepare){aria-label="Week 2 summary"} |     [🖥️](/slides/lect_07.html "Lecture slides"){aria-label="Lecture 1 slides"}     |              [📋](/ae/ae-8.html "Application exercise - 8"){aria-label="Application Exercise 0 instructions"}               |                                                     |      |         |                                                                                 |
| [7](/weeks/week-07.html)  | Mon, 10 Oct  | Association between quantitative variables | [📖](/weeks/week-07.html#prepare){aria-label="Week 2 summary"} |     [🖥️](/slides/lect_08.html "Lecture slides"){aria-label="Lecture 1 slides"}     |                                                                                                                             |                                                     |      |         |                                                                                 |
|                           | Wed, 12 Oct  | Association between random variables       |                                                                |                             [🖥️](/slides/lect_09.html)                             |              [📋](/ae/ae-9.html "Application exercise - 9"){aria-label="Application Exercise 0 instructions"}               | [✍️](/hw/hw-2.html){aria-label="HW 5 instructions"} |      |         |                                                                                 |
| [8](/weeks/week-08.html)  | Mon, 17 Oct  | Probability models for counts              | [📖](/weeks/week-08.html#prepare){aria-label="Week 2 summary"} |                             [🖥️](/slides/lect_10.html)                             |                                                                                                                             |                                                     |      |         |                                                                                 |
|                           | Wed, 19 Oct  | The normal probability model               |                                                                |                             [🖥️](/slides/lect_11.html)                             |                                                                                                                             |                                                     |      |         |                                                                                 |
| [9](/weeks/week-09.html)  | Mon, 24 Oct  | Samples and surveys                        | [📖](/weeks/week-09.html#prepare){aria-label="Week 2 summary"} |                             [🖥️](/slides/lect_12.html)                             |                                                                                                                             |                                                     |      |         |                                                                                 |
|                           | Wed, 26 Oct  | Sampling variation and quality             |                                                                |                             [🖥️](/slides/lect_13.html)                             |             [📋](/ae/ae-10.html "Application exercise - 10"){aria-label="Application Exercise 0 instructions"}              |                                                     |      |         | [📂](https://stats1010-f22.github.io/website/project-description.html#proposal) |
| [10](/weeks/week-10.html) | Mon, 31 Oct  | Revision for Exam 2                        |                                                                |                            [🖥️](/slides/halloween.html)                            |                                                                                                                             |                                                     |      |         |                                                                                 |
|                           | Wed, 2 Nov   | Exam 2                                     |                                                                |                                                                                    |                                                                                                                             |                                                     |  ✅  |         |                                                                                 |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
