---
title: "Lec 4 - Exploring numerical data"
subtitle: "STAT 1010 - Fall 2022"
footer:  "[stat1010-f22.github.io/website](https://stats1010-f22.github.io/website/)"
format: 
  revealjs: 
    theme: slides.scss
    transition: fade
    slide-number: true
editor: visual
execute:
  freeze: auto
---

```{r include = FALSE}
library(countdown)
```

# Learning outcomes

By the end of this lesson you should:

-   Understand measures of center and know how to compute them

-   Understand measures of spread and know how to compute them

-   Graphical representation and interpretation of one numerical variables in R

## Definition of numerical variable

A numerical or quantitative variable is a variable that can be measured.

## The purpose of Exploratory Data Analysis (EDA)

-   EDA is about learning the structure of a dataset through a series of numerical and graphical techniques.

-   When you do EDA, you'll look for both

    -   general trends and

    -   interesting outliers in your data.

generate questions that will help inform subsequent analysis.

# Observations {background-image="lect_04_images/observations.png" background-size="contain"}

# Variables {background-image="lect_04_images/variables.png" background-size="contain"}

# Measures of center

-   Mean

-   Median ($50\%th$ percentile)

# Mean

$\bar{x}_{var} =\frac{the\; sum\; of\; all\; the\; observations\; in\; the \; var}{the \; number \;of \;observations}$

# Measures of spread

-   Percentiles

    -   quartiles

-   
