---
title: "Chapter 9: Random variables"
subtitle: "STAT 1010 - Fall 2022"
footer:  "[stat1010-f22.github.io/website](https://stats1010-f22.github.io/website/)"
format: 
  revealjs: 
    theme: slides.scss
    transition: fade
    slide-number: true
editor: visual
execute:
  freeze: auto
---

```{r include = FALSE}
library(countdown)
library(pdftools)
```

# Learning outcomes

By the end of this lesson you should:

-   Know how to find the mean given a probabiliy mass function

-   Understand how to use expected values and variance rules

# Revision - 1

Find the mean, and variance for these examples:

1.  20, 24, 25, 36, 25, 22, 23

2.  Rolling a fair six-sided die

Revision - 2

The scientist collecting measurements with this frequency

    | Value | n   |
    |-------|-----|
    | 1.23  | 3   |
    | 1.29  | 5   |
    | 1.37  | 4   |
    | 1.84  | 1   |
    | 1.18  | 6   |
    | 1.22  | 2   |
    | 1.25  | 4   |

# Your turn

[Click here](https://stats1010-f22.github.io/website/ae/ae-8.html) or the qr code below

```{r, eval=TRUE, echo=FALSE}
library(qrcode)
qr <- qr_code("https://stats1010-f22.github.io/website/ae/ae-8.html")
plot(qr)
```
