---
title: "Introduction to probability (AE-4)"
output: 
   html_document
---

::: callout-important
This application exercise is due on 23 Sept at 2:00pm.
:::

1.  One ball will be drawn at random from a box containing: 3 cyan balls, 5 magenta balls, and 7 yellow balls. What is the probability that the ball will be cyan?

2.  What is the probability that the ball will not be cyan?

3.  Instead of taking just one draw, consider taking two draws. You take the second draw without returning the first draw to the box. We call this sampling without replacement. What is the probability that the first draw is cyan and that the second draw is not cyan?

4.  Now repeat the experiment, but this time, after taking the first draw and recording the color, return it to the box and shake the box. We call this sampling with replacement. What is the probability that the first draw is cyan and that the second draw is not cyan?

5.  Two events A and B are independent if Pr(A and B)=Pr(A)P(B). Under which situation are the draws independent?
    a. You don’t replace the draw.
    b. You replace the draw.
    c. Neither
    d. Both

6.  Say you've drawn 5 balls from the box, with replacement, and all have been yellow. What is the probability that the next one is yellow?

7.  If you roll a 6-sided die six times, what is the probability of not seeing a 6?
