---
title: "More probability rules (AE-5)"
output: 
   html_document
---

::: callout-important
This application exercise is due on 27 Sept at 2:00pm.
:::

Computers let you assemble, manipulate, and visualize data sets, all at speeds that would have wowed yesterday\'s scientists. In short, computers give you scientific superpowers! But if you wish to use them, you\'ll need to pick up some programming skills. Steve Job said that "[compu](https://medium.learningbyshipping.com/bicycle-121262546097)[ters are bicycles for our minds"](https://www.youtube.com/watch?v=L40B08nWoMk) because of the efficiency rating of humans on bicycles.

One reason computers are so incredible is that they allow us to simulate a multitude of events. Today we will simulate the probability that two of you in this section of Stat1010 have the same birthdays.

Suppose you are in a classroom with 100 people. If we assume this is a randomly selected group of 100 people, what is the chance that at least two people have the same birthday? Although it is somewhat advanced, we can deduce this mathematically. We will do this later. Here we use a Monte Carlo simulation. For simplicity, we assume nobody was born on February 29. This actually doesn\'t change the answer much.

First, note that birthdays can be represented as numbers between 1
and 365, so a sample of 100 birthdays can be obtained like this:

```{r initial_simulation}

n <- 100
bdays <- sample(1:365, n, replace = TRUE)
```
